FROM alpine:latest
# dfu-util errors
# ninja-build errors

RUN apk update; \
    apk add bison ccache cmake dfu-util flex git gperf libffi-dev libssl3 libusb ninja-build python3 wget; \
    adduser user1

WORKDIR /home/user1
USER user1
RUN git clone --depth=1 --recurse-submodules https://github.com/espressif/esp-idf.git; \
    /home/user1/esp-idf/install.sh esp32,esp32s2; \
    source /home/user1/esp-idf/export.sh;

CMD ["/bin/sh"]
