FROM ubuntu:latest
RUN apt update -y; \
    apt install -y bison ccache cmake dfu-util flex git gperf libffi-dev libssl-dev libusb-1.0-0 ninja-build python3 python3-venv wget; \
    useradd user1

WORKDIR /home/user1
USER user1
RUN git clone --depth=1 --recurse-submodules https://github.com/espressif/esp-idf.git; \
    /home/user1/esp-idf/install.sh esp32,esp32s2;
    source /home/user1/esp-idf/export.sh; \

CMD ["/usr/bin/bash"]
